### ISSUE TITLE
Approvazione Project plan

### ISSUE THREAD

**Issue by mathieuteti2002** [mathieuteti2002/Progetto_ING_SW#3]
Versione ultimata del **project plan**, richiediamo cortesemente l'approvazione
[Project_Planning_Finale.pdf](https://github.com/mathieuteti2002/Progetto_ING_SW/files/13852967/Project_Planning_Finale.pdf)

**Comment by garganti** [comment]
approvo però attenti:

- va bene che usiate Figma, ma anche github ha con i project i kanban che possono essere utili
- NON va bene che carichiate su github lo zip del codice: NON potete usare github come repository di file, deve essere integrato con lo sviluppo del codice. NON potete scrivere codice in locale e poi ogni tanto caricare con upload il codice su github. Dico così  perchè ho visto uno zip nella root.
